### PR TITLE
feat: update schema and sdks

### PR DESCRIPTION
**Pull request by dirien**
Hi @ringods,

this PR updates the schema and sdks.

### CODE REVIEW

**Comment by ringods** [comment]
@dirien is it OK that all the `Example usage` comments are gone from the generated SDKs?

**Comment by dirien** [comment]
@ringods What could be the reason for this?

**Comment by dirien** [comment]
I checked, there was no update from the underlying aquasec tf provider.

**Comment by dirien** [comment]
@ringods should be good now :/

**Review by ringods — APPROVED** [review]

**Pull request merged**
