### PR TITLE
feat: pin dependecies in GitHub action

### PR DESCRIPTION
**Pull request by dirien**
This PR pins all dependencies in the GitHub action.

### CODE REVIEW

**Comment by ringods** [comment]
@dirien why are you pinning the versions on a commit? My idea was to pin on a full semver (major.minor.build) and then let Dependabot bump to newer versions explicitely, like you see happening here in PR #8

**Comment by dirien** [comment]
> Pinned dependencies reduce several security risks:
> 
> - They ensure that checking and deployment are all done with the same
> 
> software, reducing deployment risks, simplifying debugging, and enabling
> 
> reproducibility.
> 
> - They can help mitigate compromised dependencies from undermining the
> 
> security of the project (in the case where you've evaluated the pinned
> 
> dependency, you are confident it's not compromised, and a later version is
> 
> released that is compromised).
> 
> - They are one way to [counter dependency confusion (aka substitution) attacks](https://azure.microsoft.com/en-us/resources/3-ways-to-mitigate-risk-using-private-package-feeds/),
> 
> in which an application uses multiple feeds to acquire software packages (a
> 
> "hybrid configuration"), and attackers fool the user into using a malicious
> 
> package via a feed that was not expected for that package.

All derived from the OSSF Security Scorecards -> https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies

Dependabot will update the commend after the action with the tag 

```yaml
actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2
```

I added the # tags in this PR by hand to make it more clear! It's all about secure software supply chain.

**Comment by ringods** [comment]
If Dependabot can bump from one tag to another, but puts the corresponding commit in there, I'm OK with this setup. What I want to prevent is that every commit in an GH action repo would trigger a PR here.

**Comment by dirien** [comment]
Shy ping healthcheck on this PR. Any feedback regarding the pinning of the dependencies?

**Comment by ringods** [comment]
@dirien I forgot to approve after I asked for the internals on how Dependabot behaves. Will do this now.

In the meantime, I am working on a system similar to Pulumi's [ci-mgmt](https://github.com/pulumi/ci-mgmt/), where the workflows will be generated in all provider repositories to keep the workflows consistent. I will have to see how to tackle version changes there.

**Review by ringods — APPROVED** [review]

**Pull request merged**
